Fix workflow

diff --git a/.github/workflows/generate.yml b/.github/workflows/generate.yml
--- a/.github/workflows/generate.yml
+++ b/.github/workflows/generate.yml
@@ -16,7 +16,12 @@ jobs:
     steps:
     - name: Check client_payload
       if: ${{ ! (github.event.client_payload.origin_ref && contains(github.event.client_payload.origin_ref, 'refs/tags/')) }}
-      run: exit 1
+      run: |
+        echo ${{ event }}
+        echo '::error::Invalid request'
+        exit 1
+      env:
+        EVENT: ${{ toJson(github.event) }}
 
     - uses: actions/github-script@v2
       id: release_tag
